// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ChessBoard from "./ChessBoard.bs.js";

function App(props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Chess Board"), React.createElement(ChessBoard.make, {}));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
