// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function ChessBoard(props) {
  var letters = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h"
  ];
  var getRowClass = function (row) {
    if (row % 2 === 0) {
      return "even-row";
    } else {
      return "odd-row";
    }
  };
  return React.createElement("div", {
              id: "chess-board"
            }, $$Array.init(8, (function (row) {
                    var row$1 = row + 1 | 0;
                    var rowClass = getRowClass(row$1);
                    return React.createElement("div", {
                                className: "chess-row " + rowClass
                              }, $$Array.init(8, (function (col) {
                                      var col$1 = col + 1 | 0;
                                      var squareContent = row$1 !== 1 ? (
                                          col$1 !== 1 ? null : React.createElement("div", {
                                                  className: "col-1"
                                                }, Caml_array.get(letters, row$1 - 1 | 0))
                                        ) : React.createElement("div", {
                                              className: "row-1"
                                            }, String(col$1));
                                      return React.createElement("div", {
                                                  className: "square"
                                                }, squareContent);
                                    })));
                  })));
}

var make = ChessBoard;

export {
  make ,
}
/* react Not a pure module */
