// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.bs.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client from "react-dom/client";

var Root = {};

var Client$1 = {
  Root: Root
};

var rootElement = document.getElementById("root");

if (rootElement == null) {
  console.log("Root element not found");
} else {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement(Test.make, {}));
}

var rootElement$1 = (rootElement == null) ? undefined : Caml_option.some(rootElement);

export {
  Client$1 as Client,
  rootElement$1 as rootElement,
}
/* rootElement Not a pure module */
