// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Dropdown from "./Dropdown.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Form(props) {
  var match = React.useState(function () {
        return "";
      });
  var setFenBoard = match[1];
  var fenBoard = match[0];
  React.useState(function () {
        return "";
      });
  React.useState(function () {
        return "";
      });
  var match$1 = React.useState(function () {
        return "";
      });
  var setNextFenBoard = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setIsSubmitted = match$2[1];
  var colorDropdownItems = [
    {
      id: "1",
      text: "White"
    },
    {
      id: "2",
      text: "Black"
    }
  ];
  var difficultyDropdownItems = [
    {
      id: "1",
      text: "1"
    },
    {
      id: "2",
      text: "2"
    },
    {
      id: "3",
      text: "3"
    },
    {
      id: "4",
      text: "4"
    },
    {
      id: "5",
      text: "5"
    }
  ];
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    var endpoint = "http://localhost:8080/get_suggested_move?";
    var queryString = "board=" + fenBoard + "&color=" + encodeURIComponent("W") + "&difficulty=" + encodeURIComponent("1");
    Curry._1(setIsSubmitted, (function (param) {
            return true;
          }));
    Curry._1(setNextFenBoard, (function (param) {
            return "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR";
          }));
    console.log(endpoint + queryString);
    var getMove = async function (query) {
      console.log("test");
      var response = await fetch(query);
      console.log("test2");
      var json = await response.json();
      Curry._1(setNextFenBoard, (function (param) {
              return JSON.stringify(json);
            }));
      console.log(JSON.stringify(json));
    };
    var move = getMove(endpoint + queryString);
    console.log(move);
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("form", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("input", {
                                      className: "border-2 border-gray-300 bg-white h-10 px-5 py-2 w-96 rounded-lg text-sm focus:outline-none",
                                      placeholder: "FEN board",
                                      type: "text",
                                      value: fenBoard,
                                      onChange: (function ($$event) {
                                          Curry._1(setFenBoard, $$event.currentTarget.value);
                                        })
                                    }),
                                JsxRuntime.jsx(Dropdown.make, {
                                      items: colorDropdownItems,
                                      placeholder: "Select a color"
                                    }),
                                JsxRuntime.jsx(Dropdown.make, {
                                      items: difficultyDropdownItems,
                                      placeholder: "Select a difficulty"
                                    })
                              ],
                              className: "flex items-center space-x-4"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Submit",
                              className: "mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded",
                              type: "submit"
                            })
                      ],
                      onSubmit: handleSubmit
                    }),
                match$2[0] ? JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("img", {
                                className: "h-96 w-96",
                                src: "https://fen2image.chessvision.ai/" + fenBoard
                              }),
                          JsxRuntime.jsx("img", {
                                className: "h-96 w-48",
                                src: "./arrow.svg"
                              }),
                          JsxRuntime.jsx("img", {
                                className: "h-96 w-96",
                                src: "https://fen2image.chessvision.ai/" + match$1[0]
                              })
                        ],
                        className: "flex py-5"
                      }) : null
              ]
            });
}

var make = Form;

export {
  make ,
}
/* react Not a pure module */
