// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

function Textbox(props) {
  var onChange = props.onChange;
  var placeholder = props.placeholder;
  var placeholder$1 = placeholder !== undefined ? placeholder : "Enter text here";
  return JsxRuntime.jsx("input", {
              className: "border-2 border-gray-300 bg-white h-10 px-5 py-2 w-96 rounded-lg text-sm focus:outline-none",
              placeholder: placeholder$1,
              type: "text",
              value: props.value,
              onChange: (function ($$event) {
                  Curry._1(onChange, (function (param) {
                          return $$event.currentTarget.value;
                        }));
                })
            });
}

var make = Textbox;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
